[package]
name = "ukubulala-srv"
version = "0.1.0"
authors = ["Wojciech Bartnik <yisonPylkita@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
diesel = { version = "1.4", features = ["postgres"] }
dotenv = "0.15"
