version: "3.8"
services:
  # server:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/code
  #     - logvolume01:/var/log
  #   links:
  #     - database
  database:
    build: db
    # environment:
    #   POSTGRES_PASSWORD: docker
    network_mode: bridge
    ports:
      - "5432:5432"
    env_file:
      - database.env
    # volumes:
    #   - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  logvolume01: {}
  # database-data: {}