#[derive(Queryable)]
pub struct Homicide {
    pub record_id: i32,
    pub agency_code: Option<String>,
    pub agency_name: Option<String>,
    pub agency_type: Option<String>,
    pub city: Option<String>,
    pub state: Option<String>,
    pub year: Option<String>,
    pub month: Option<String>,
    pub incident: Option<String>,
    pub crime_type: Option<String>,
    pub crime_solved: Option<String>,
    pub victim_sex: Option<String>,
    pub victim_age: Option<String>,
    pub victim_race: Option<String>,
    pub victim_ethnicity: Option<String>,
    pub perpetrator_sex: Option<String>,
    pub perpetrator_age: Option<String>,
    pub perpetrator_race: Option<String>,
    pub perpetrator_ethnicity: Option<String>,
    pub relationship: Option<String>,
    pub weapon: Option<String>,
    pub victim_count: Option<String>,
    pub perpetrator_count: Option<String>,
    pub record_source: Option<String>,
}