on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: build

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            prifile: minimal
# TODO: add Clippy and rustfmt to build'n'validation process
#            components: rustfmt, clippy 
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
